all:
	g++ -IC:\vs_dev_lib\lib\include src/*.cpp -LC:\mingw64\lib\SDL2-2.0.5\x86_64-w64-mingw32\lib -o pewpew -lmingw32 -lSDL2main -lSDL2 -std=c++11 -g
#g++ src/*.cpp -ID:\dev\SDL_32\include\SDL2 -ID:\dev -LD:\dev\SDL_32\lib -lmingw32 -lSDL2main -lSDL2 -std=c++11 -o pewpew -g
